pages:
  stage: build
  image: alpine
  script:
    - apk add --update doxygen ttf-freefont graphviz
    - doxygen doc/openQmin_documentation
    - mv doc/doxygenOutput/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
