pages:
  stage: build
  image: ubuntu:trusty
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -yq update
    - apt-get -yq install graphviz
    - apt-get -yq install doxygen
    - doxygen doc/landauDeGUI_documentation
    - mv doc/doxygenOutput/html/ public/
  artifacts:
    paths:
      - public
