pages:
  stage: build
  image: alpine
  script:
    - apk update && apk add doxygen
    - doxygen doc/landauDeGUI_documentation
    - mv doc/doxygenOutput/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
